name: serialization-bench
dependencies:
  - python=3.7
  - ipython
  - cython
  - pandas
  - jupyterlab
  - pyarrow=0.11.1  # parquet

  - pip:
    - altair
    - pymongo==3.7.2  # bson
    - cbor==1.0.0
    - msgpack==0.5.6
    - protobuf==3.6.1
    - ujson==1.35
